package com.example.matchdomain.donation.entity.flameEnum;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum AdjectiveFlame {
    SMALL("작은"),
    BRIGHT("누구보다 밝은"),
    MANY("잠이 많은"),
    FEW("걱정이 적은"),
    GOOD("기분이 좋은"),
    PRETTY("폰 케이스가 예쁜"),
    UGLY("추운 날을 좋아하는"),
    HOT("누구보다 따뜻한"),
    CUTE("귀여운"),
    COOL("멋진 신발을 가진"),
    VARIOUS("간식을 많이 가진"),
    UNIQUE("유니크한"),
    SPECIAL("특별한 잠버릇이 있는"),
    ORDINARY("평범한날이 좋은"),
    MYSTERIOUS("신비로운"),
    ELEGANTED("우아한 노래를 듣는"),
    SOFT("부드러운 빵이 좋은"),
    LOVELY("사랑스러운"),
    CHARMING("매력적인 이마를 가진"),
    ELEGANT("고급스러운 텀블러를 가진"),
    MAGICAL("마법같이 나타난"),
    POWERFUL("강력한 화력의"),
    BRILLIANT("맑은 날을 좋아하는"),
    FANTASTIC("환상적인 식사를 한"),
    MYSTICAL("신기한 나라 물약을 먹고 커진"),
    PEACEFUL("평화로운 하루를 보내는"),
    ENERGETIC("활기찬 불꽃을 가진"),
    DAZZLING("방금 일어나 눈이 부신"),
    COLORFUL("색깔이 풍부한"),
    GENTLE("온화한 입은"),
    WILD("야생 다큐를 좋아하는"),
    ADVENTUROUS("모험적인"),
    CHILL("시크한"),
    CRISP("의외로 시원한"),
    FRESH("신선한 야채를 키우는"),
    FLOWING("미끄럼틀 타는"),
    SPARKLING("반짝이는"),
    GLITTERING("빛이 나는"),
    FLYING("날아다니는"),
    DANCING("요즘 춤을 배우는"),
    WHISPERING("나무에게 속삭이는"),
    SINGING("노래하는"),
    LAUGHING("강아지만 보면 웃는"),
    JUMPING("점프가 취미인"),
    FADING("바람과 함께 사라지는"),
    BURNING("불타는 열정의"),
    EXPLODING("부끄러움이 많은"),
    CRACKLING("말랑말랑"),
    POPPING("팝핀"),
    ZIGZAG("지그재그로 걷는"),
    SHOWERING("소나기 소리가 좋은"),
    DRIZZLING("이슬비가 좋은"),
    DRENCHING("비오는 소리를 듣는"),
    SPLENDID("화려한 조명이 감싸는"),
    GORGEOUS("화려한 옷을 살 예정인"),
    GRACEFUL("우아한"),
    FANCY("화려한 케이크를 받은"),
    GLAMOROUS("매력적인 장바구니를 가진"),
    BIG("의외로 큰"),
    LITTLE_SMALL("의외로 작은"),
    FAST("누구보다 빠른"),
    SLOW("잠 드는게 조금 느린"),
    HIGH("시력이 높은"),
    LOW("앉은 키가 낮은"),
    DARK("다크 커피를 좋아하는"),
    BRIGHTNESS("밝은"),
    FEW_FLAME("적은 장작으로도 잘 타는"),
    GOOD_NIGHT("좋은 잠을 잔"),
    NEW("새로운 전세집을 찾는"),
    OLD("오래된 식탁이 좋은"),
    EXPENSIVE("비싼 A4 용지를 먹은"),
    HEAVY("무거운 가방도 잘드는"),
    LIGHT("가벼운 핸드폰이 좋은"),
    NICE("근사한 식사를 한"),
    COLD("추워도 아아 먹는"),
    HOT_AMERICANO("더운날 뜨아 먹는"),
    BUSY("바쁜척 하고 싶은"),
    QUIET("한적한 시골이 좋은"),
    TALL("높은 발화점을 가진"),
    SHORT("낮은 발화점을 가진"),
    STRONG("강한 멘탈을 가진"),
    HAPPY("행복한 내일을 기다리는"),
    SAD("슬픈 눈의"),
    SLEEPY("졸린 눈의"),
    FUNNY("재미있는 영화를 본"),
    PRETTY_BALL_PEN("예쁜 볼펜을 모으는"),
    CUTE_VIDEO("귀여운 영상을 모으는"),
    GLAD("기쁜 소식을 가져오는");

    private final String value;
}
