package com.example.matchdomain.donation.entity.flameEnum;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum AdjectiveFlame {
    BIG_FLAME("큰 불꽃을 입은"),
    SMALL_FLAME("작은 불꽃을 입은"),
    FAST_FLAME("빠른 불꽃을 입은"),
    SLOW_FLAME("느린 불꽃을 입은"),
    HIGH_FLAME("높은 불꽃을 입은"),
    LOW_FLAME("낮은 불꽃을 입은"),
    DARK_FLAME("어두운 불꽃을 입은"),
    BRIGHT_FLAME("밝은 불꽃을 입은"),
    MANY_FLAMES("많은 불꽃을 입은"),
    FEW_FLAMES("적은 불꽃을 입은"),
    GOOD_FLAME("좋은 불꽃을 입은"),
    BAD_FLAME("나쁜 불꽃을 입은"),
    PRETTY_FLAME("예쁜 불꽃을 입은"),
    UGLY_FLAME("추운 불꽃을 입은"),
    HOT_FLAME("더운 불꽃을 입은"),
    CUTE_FLAME("깜찍한 불꽃을 입은"),
    COOL_FLAME("멋진 불꽃을 입은"),
    SEXY_FLAME("섹시한 불꽃을 입은"),
    VARIOUS_FLAMES("다양한 불꽃을 입은"),
    UNIQUE_FLAME("유니크한 불꽃을 입은"),
    SPECIAL_FLAME("특별한 불꽃을 입은"),
    ORDINARY_FLAME("평범한 불꽃을 입은"),
    MYSTERIOUS_FLAME("신비로운 불꽃을 입은"),
    ELEGANTED_FLAME("우아한 불꽃을 입은"),
    SOFT_FLAME("부드러운 불꽃을 입은"),
    ROUGH_FLAME("거친 불꽃을 입은"),
    LOVELY_FLAME("사랑스러운 불꽃을 입은"),
    CHARMING_FLAME("매력적인 불꽃을 입은"),
    ELEGANT_FLAME("고급스러운 불꽃을 입은"),
    MAGICAL_FLAME("마법적인 불꽃을 입은"),
    POWERFUL_FLAME("강력한 불꽃을 입은"),
    BRILLIANT_FLAME("찬란한 불꽃을 입은"),
    FANTASTIC_FLAME("환상적인 불꽃을 입은"),
    MYSTICAL_FLAME("신비한 불꽃을 입은"),
    PEACEFUL_FLAME("평화로운 불꽃을 입은"),
    ENERGETIC_FLAME("활기찬 불꽃을 입은"),
    DAZZLING_FLAME("눈부신 불꽃을 입은"),
    COLORFUL_FLAME("색상이 풍부한 불꽃을 입은"),
    GENTLE_FLAME("온화한 불꽃을 입은"),
    WILD_FLAME("야생적인 불꽃을 입은"),
    ADVENTUROUS_FLAME("모험적인 불꽃을 입은"),
    CHILL_FLAME("차가운 불꽃을 입은"),
    CRISP_FLAME("시원한 불꽃을 입은"),
    FRESH_FLAME("신선한 불꽃을 입은"),
    FLOWING_FLAME("흐르는 불꽃을 입은"),
    SPARKLING_FLAME("반짝이는 불꽃을 입은"),
    FLICKERING_FLAME("희미하게 번뜩이는 불꽃을 입은"),
    GLITTERING_FLAME("빛나는 불꽃을 입은"),
    RADIANT_FLAME("빛나는 불꽃을 입은"),
    SHIMMERING_FLAME("희미하게 빛나는 불꽃을 입은"),
    SHINING_FLAME("빛나는 불꽃을 입은"),
    GLOWING_FLAME("빛나는 불꽃을 입은"),
    FLYING_FLAME("날아가는 불꽃을 입은"),
    DANCING_FLAME("춤추는 불꽃을 입은"),
    WHISPERING_FLAME("속삭이는 불꽃을 입은"),
    SINGING_FLAME("노래하는 불꽃을 입은"),
    LAUGHING_FLAME("웃는 불꽃을 입은"),
    CRYING_FLAME("울고 있는 불꽃을 입은"),
    JUMPING_FLAME("뛰어오르는 불꽃을 입은"),
    FADING_FLAME("사라지는 불꽃을 입은"),
    BURNING_FLAME("불타는 불꽃을 입은"),
    EXPLODING_FLAME("터지는 불꽃을 입은"),
    CRACKLING_FLAME("말랑말랑 불꽃을 입은"),
    POPPING_FLAME("팝팝 불꽃을 입은"),
    ZIPPING_FLAME("징징 불꽃을 입은"),
    ZIGZAG_FLAME("지그재그 불꽃을 입은"),
    SHOWERING_FLAME("소나기 불꽃을 입은"),
    DRIZZLING_FLAME("이슬비 불꽃을 입은"),
    DRENCHING_FLAME("비오는 불꽃을 입은"),
    SPLENDID_FLAME("화려한 불꽃을 입은"),
    GORGEOUS_FLAME("화려한 불꽃을 입은"),
    GRACEFUL_FLAME("우아한 불꽃을 입은"),
    FANCY_FLAME("화려한 불꽃을 입은"),
    GLAMOROUS_FLAME("매혹적인 불꽃을 입은");

    private final String value;
}
